### ISSUE TITLE
Pokemon type not included in damage (Stab damage)

### ISSUE THREAD

**Issue by Armorio** [caffyn/PTUMoveMaster#2]
When using the macro to use a pokemon's attack, its type is not taken into account for damage when it stabs.

Use roll button on character sheet
![image](https://user-images.githubusercontent.com/56073362/108744769-9c8d7000-753a-11eb-83bd-39dc9711ff53.png)

Use macro
![image](https://user-images.githubusercontent.com/56073362/108745068-f5f59f00-753a-11eb-8ff2-6b67b87c149f.png)

**Comment by GSV-a-Nest-of-Kindled-Embers** [comment]
Fixed in patch https://github.com/caffyn/PTUMoveMaster/commit/986e8cf1e926e9bffbefb57e9d4848fcc54316b0 .
