### ISSUE TITLE
Bug: Abilities give out the wrong effect in the chat

### ISSUE THREAD

**Issue by MrMars5555** [caffyn/PTUMoveMaster#31]
When an ability is clicked in the token's combat menu it sends to chat the effect of either another move, capability, or another ability. This occurs with linked and un-linked tokens. If an new ability is added, all abilities now say the new ability. hovering over the ability in the combat menu still gives the correct information.
![image](https://user-images.githubusercontent.com/85539100/121123209-d5530b80-c7f0-11eb-8a6c-a5c412dc4782.png)

**Comment by GSV-a-Nest-of-Kindled-Embers** [comment]
I *think* I've fixed this in https://github.com/caffyn/PTUMoveMaster/commit/dd6a76b3c5f8dafd2b4acc25185bc2d50355101d , but let me know if you see it occur again.
