### ISSUE TITLE
Add automation with Last Chance abilities

### ISSUE THREAD

**Issue by MrMars5555** [caffyn/PTUMoveMaster#41]
Last Chance: Last Chance Abilities are always associated with an Elemental Type. The user gains a +5 bonus to Damage Rolls when using attacks of that Type. This bonus increases to +10 when the user is under 1/3rd of their Maximum Hit Points.

**Comment by GSV-a-Nest-of-Kindled-Embers** [comment]
Last Chance automation is already implemented - the user just has to edit the name of the ability to include the type in parentheses after Last Chance, so the module knows what type of move to apply it to.

Example:
> Last Chance (Normal)

![image](https://user-images.githubusercontent.com/69528253/123168325-d2d5f000-d445-11eb-804d-d654bd54a696.png)


![image](https://user-images.githubusercontent.com/69528253/123168312-cea9d280-d445-11eb-9474-0135e2e86aa4.png)
